"""
Turns the scraped data/techniques.json into techniques.js for the game.

Run it again whenever you re-scrape:
    python convert.py

Why a .js file and not the .json directly? Browsers refuse to load a .json
file when you just double-click index.html. A .js file always works.
This script also drops fields the game doesn't use, so the app stays fast.
"""
import json
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / "data" / "techniques.json"
OUT = HERE / "techniques.js"

# Grade order from lowest to highest. Unknown grades are added at the end.
GRADES = ["6th kyu", "5th kyu", "4th kyu", "3rd kyu", "2nd kyu", "1st kyu", "1st dan"]


def slugs(items):
    return [i["slug"] for i in items or [] if i.get("slug")]


def grade_rank(g):
    return GRADES.index(g) if g in GRADES else len(GRADES)


def convert(t):
    grades = sorted(t.get("belt_level") or [], key=grade_rank)
    combos = t.get("combinations") or {}
    return {
        "id": t["slug"],
        "name": t["name"],
        "kanji": t.get("kanji", ""),
        "translation": t.get("english", ""),
        "category": t.get("category", ""),
        "subcategory": t.get("subcategory", ""),
        "difficulty": t.get("difficulty_level") or 2,  # 1 Beginner, 2 Intermediate, 3 Advanced
        "grade": grades[0] if grades else "",          # lowest grade it's taught at
        "grades": grades,
        "videos": [{"yt": v["youtube_id"], "title": v.get("title", ""), "channel": v.get("channel", "")}
                   for v in t.get("videos") or [] if v.get("youtube_id")],
        "overview": t.get("overview", ""),
        "phases": [{"label": f"{k.capitalize()} · {p.get('label', '')}", "text": p.get("text", "")}
                   for k, p in (t.get("phases") or {}).items()],
        "steps": [{"title": s.get("title", ""), "text": s.get("text", "")} for s in t.get("steps") or []],
        "principles": t.get("principles") or [],
        "mistakes": [{"mistake": m.get("mistake", ""), "fix": m.get("fix", "")} for m in t.get("mistakes") or []],
        "when": t.get("when_to_use", ""),
        "setups": slugs(combos.get("attack_these_first")),
        "followUps": slugs(combos.get("follow_up_with")),
        "counters": slugs(t.get("counters")),
        "related": slugs(t.get("related")),
        "source": t.get("url", ""),
    }


data = json.loads(SRC.read_text(encoding="utf-8"))
techniques = sorted((convert(t) for t in data), key=lambda t: t["name"].lower())

ids = [t["id"] for t in techniques]
dupes = {i for i in ids if ids.count(i) > 1}
if dupes:
    raise SystemExit(f"Duplicate ids: {dupes}")

OUT.write_text(
    "// GENERATED by convert.py from data/techniques.json. Don't edit by hand;\n"
    "// put your own notes in my-notes.js instead.\n"
    f"window.GRADES = {json.dumps(GRADES)};\n"
    "window.TECHNIQUES = " + json.dumps(techniques, ensure_ascii=False, separators=(",", ":")) + ";\n",
    encoding="utf-8",
)
print(f"Wrote {len(techniques)} techniques to {OUT.name} ({OUT.stat().st_size // 1024} KB)")
